---
title: "Social Media"
date: "Update `r format(Sys.time(),'%d. %m. %Y')`"
author: "Ondrej Pekacek/TI CZ"
output: 
  flexdashboard::flex_dashboard:
    logo: "data/logo_ti.png"
    theme: cosmo
    orientation: columns
    vertical_layout: fill
    source_code: https://github.com/opop999/election_monitoring_social_media_communication
    navbar:
      - {title: "Project", icon: "ion-information-circled", href: "https://www.transparentnivolby.cz/snemovna2021"}
      - {title: "Author", icon: "ion-social-linkedin", href: "https://www.linkedin.com/in/ondrej-pekacek"}
      - {title: "Data: Hlidac Statu", icon: "ion-cloud", href: "https://www.hlidacstatu.cz/data/Index/vyjadreni-politiku"}
      - {title: "Data: Twitter", icon: "ion-cloud", href: "https://developer.twitter.com/en/docs/twitter-api"}
---

```{r setup, include=FALSE}
# Disable scientific notation of numbers
options(scipen = 999)

# Package names
packages <- c("dplyr", "ggplot2", "plotly", "htmlwidgets", "stringr", "tidyr")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))

# Directory where summary data were saved
dir_name <- "data"

# Import summary datasets
summary_dataset_yt <- readRDS(file = paste0(dir_name, "/summary_tables/total_summary_yt.rds"))
summary_dataset_fb <- readRDS(file = paste0(dir_name, "/summary_tables/total_summary_fb.rds"))
summary_dataset_tw <- readRDS(file = paste0(dir_name, "/summary_tables/total_summary_tw.rds"))

time_dataset_yt <- readRDS(file = paste0(dir_name, "/summary_tables/time_summary_yt.rds"))
time_dataset_fb <- readRDS(file = paste0(dir_name, "/summary_tables/time_summary_fb.rds"))
time_dataset_tw <- readRDS(file = paste0(dir_name, "/summary_tables/time_summary_tw.rds"))

# Specify output directory for individual plots
directory <- "data/html_plots"

# Check whether output directory exists to save individual plots
if (!dir.exists(directory)) {
  dir.create(directory)
} else {
  print("Output directory already exists")
}

# Election date for vertical line in the time-plots
election_date <- as.Date("2021-10-08")

# Graph zoom date end & beginning
start_date <- as.Date("2021-01-01")
end_date <- as.Date("2021-11-05")

```

Twitter {data-navmenu="Platform Summaries"}
=====================================

Column {.tabset}
-----------------------------------------------------------------------

### **TOTAL TWEETS**

```{r}
plot_summary_dataset_tw_tweets <- ggplotly(
    summary_dataset_tw %>%
  	pivot_longer(cols = c("total_posts",
                            "total_retweets"), names_to = "type", values_to = "tweets_type_count") %>%
  	mutate(type = factor(type, levels = c("total_retweets", "total_posts"), labels = c("Retweets", "Original Posts"))) %>% 
    ggplot(aes(x = tweets_type_count, y = reorder(entity_name, total_posts_and_retweets), fill = type)) +
    geom_col() +
    scale_x_continuous(
      breaks = seq(0, 20000, 1000),
      labels = seq(0, 20000, 1000)
    ) +
    theme_minimal() +
    labs(fill = "Content Type") +
    ylab(element_blank()) +
    xlab("Original Tweets (Posts, Quotes, Replies) and Retweets") +
    ggtitle(paste("Total Tweets and Retweets (based on Twitter API) since", format(start_date, "%d.%m.%Y")))
)

plot_summary_dataset_tw_tweets

htmlwidgets::saveWidget(plot_summary_dataset_tw_tweets, file = paste0(directory, "/plot_summary_dataset_tw_tweets.html"))

```

### **TOTAL FOLLOWERS**

```{r}
plot_summary_dataset_tw_followers <- ggplotly(
  summary_dataset_tw %>%
    ggplot(aes(x = total_followers_thousands, y = reorder(entity_name, total_followers_thousands))) +
    geom_col(fill = "#14171A") +
    scale_x_continuous(
      breaks = seq(0, 10000, 50),
      labels = seq(0, 10000, 50)
    ) +
    theme_minimal() +
    ylab(element_blank()) +
    xlab("Total Followers (thousands)") +
    ggtitle(paste("Total Followers (thousands, based on Twitter API) since", format(start_date, "%d.%m.%Y")))
)

plot_summary_dataset_tw_followers

htmlwidgets::saveWidget(plot_summary_dataset_tw_followers, file = paste0(directory, "/plot_summary_dataset_tw_followers.html"))

```

### **TOTAL INTERACTIONS**

```{r}
plot_summary_dataset_tw_interactions <- ggplotly(
  summary_dataset_tw %>%
    ggplot(aes(x = total_interactions_thousands, y = reorder(entity_name, total_interactions_thousands))) +
    geom_col(fill = "#657786") +
    scale_x_continuous(
      breaks = seq(0, 10000, 250),
      labels = seq(0, 10000, 250)
    ) +
    theme_minimal() +
    ylab(element_blank()) +
    xlab("Total Interactions (retweet/comment/quote, in thousands)") +
    ggtitle(paste("Total Interactions (thousands, based on Twitter API) since", format(start_date, "%d.%m.%Y")))
)

plot_summary_dataset_tw_interactions

htmlwidgets::saveWidget(plot_summary_dataset_tw_interactions, file = paste0(directory, "/plot_summary_dataset_tw_interactions.html"))

```

### **TWEET SOURCES**

```{r}
 plot_summary_dataset_tw_sources <- ggplotly(
   summary_dataset_tw %>%
    pivot_longer(cols = c("total_source_iphone",
                          "total_source_android",
                          "total_source_web",
                          "total_source_tweet_deck",
                          "total_source_ipad",
                          "total_source_media_studio"), names_to = "source", values_to = "tweets_from_source") %>%
   	mutate(source = factor(source,
   												 levels = c("total_source_android",
   												 					 	"total_source_ipad",
   												 					  "total_source_iphone",
						                          "total_source_media_studio",
   												 					 	"total_source_tweet_deck",
						                          "total_source_web"),
   											  labels = c("Android",
   											  					 "Ipad",
   											  					 "Iphone",
   											  					 "Media Studio",
   											  					 "Tweet Deck",
   											  					 "Web"))) %>%
    ggplot(aes(x = tweets_from_source, y = reorder(entity_name, total_posts_and_retweets), fill = source)) +
    geom_col() +
    # facet_wrap(vars(source)) +
    scale_x_continuous(
      breaks = seq(0, 20000, 1000),
      labels = seq(0, 20000, 1000)
    ) +
    theme_minimal() +
   	labs(fill = "Technology used") +
    ylab(element_blank()) +
    xlab("Total Tweets and Retweets from specific device") +
    ggtitle(paste("Total Tweets and Retweets by device (based on Twitter API) since", format(start_date, "%d.%m.%Y")))
)

plot_summary_dataset_tw_sources

htmlwidgets::saveWidget(plot_summary_dataset_tw_sources, file = paste0(directory, "/plot_summary_dataset_tw_sources.html"))

```

Facebook {data-navmenu="Platform Summaries"}
=====================================

Column {.tabset}
-----------------------------------------------------------------------

### **TOTAL POSTS ON PUBLIC FACEBOOK PAGES**

```{r}
plot_summary_dataset_fb <- ggplotly(
  summary_dataset_fb %>%
    ggplot(aes(x = total_posts, y = reorder(entity_name, total_posts), fill = words_per_post)) +
    geom_col() +
    scale_fill_gradient2(
      low = "#6885c1", high = "#4267B2",
    ) +
    scale_x_continuous(
      breaks = seq(0, 10000, 250),
      labels = seq(0, 10000, 250)
    ) +
    scale_y_discrete(labels = (levels(reorder(summary_dataset_fb$entity_name, summary_dataset_fb$total_posts)) %>%
      str_replace_all(pattern = "([^a-zA-Z])", replacement = " ") %>%
      str_trim() %>%
      str_to_title())) +
    theme_minimal() +
    ylab(element_blank()) +
    xlab("Total Posts") +
    labs(fill = "Words per Post") +
    ggtitle(paste("Total FB posts (based on Hlidac Statu database) since", format(start_date, "%d.%m.%Y")))
)

plot_summary_dataset_fb

htmlwidgets::saveWidget(plot_summary_dataset_fb, file = paste0(directory, "/plot_summary_dataset_fb.html"))

```

### **PROPORTION OF SPONSORED FACEBOOK POSTS**

```{r}
plot_summary_dataset_fb_sponsored <- ggplotly(
  summary_dataset_fb %>%
    ggplot(aes(x = proportion_sponsored, y = reorder(entity_name, proportion_sponsored), fill = proportion_sponsored)) +
    geom_col() +
    geom_vline(aes(xintercept = 0.5, color = "#db0b50")) +
    scale_fill_continuous(
      low = "#a4b6da",
      high = "#4267B2"
    ) +
    scale_y_discrete(labels = (levels(reorder(summary_dataset_fb$entity_name, summary_dataset_fb$proportion_sponsored)) %>%
      str_replace_all(pattern = "([^a-zA-Z])", replacement = " ") %>%
      str_trim() %>%
      str_to_title())) +
    scale_x_continuous(
      limits = c(0, 1),
      breaks = seq(0, 1, 0.1),
      labels = c("0%", "10%", "20%", "30%", "40%", "50%", "60%", "70%", "80%", "90%", "100%")
    ) +
    theme_minimal() +
    theme(legend.position = "none") +
    xlab("Proportion sponsored posts (FB Ads library x Hlidac Statu database)") +
    ylab(element_blank()) +
    ggtitle(paste("Proportion of sponsored posts (based on Hlidac Statu and FB Ads Library database) since", format(start_date, "%d.%m.%Y")))
)

plot_summary_dataset_fb_sponsored

htmlwidgets::saveWidget(plot_summary_dataset_fb_sponsored, file = paste0(directory, "/plot_summary_dataset_fb_sponsored.html"))

```

YouTube {data-navmenu="Platform Summaries"}
=====================================

Column {.tabset}
-----------------------------------------------------------------------

### **TOTAL YOUTUBE VIDEOS**

```{r}
plot_summary_dataset_yt <- ggplotly(
  summary_dataset_yt %>%
    ggplot(aes(x = total_posts, y = reorder(entity_name, total_posts))) +
    geom_col(fill = "#ff0000") +
    scale_x_continuous(
      breaks = seq(0, 10000, 50),
      labels = seq(0, 10000, 50)
    ) +
    scale_y_discrete(labels = (levels(reorder(summary_dataset_yt$entity_name, summary_dataset_yt$total_posts)) %>%
      str_replace_all(pattern = "([^a-zA-Z])", replacement = " ") %>%
      str_trim() %>%
      str_to_title())) +
    theme_minimal() +
    ylab(element_blank()) +
    xlab("Total Videos") +
    ggtitle(paste("Total YT Videos (based on Hlidac Statu database) since", format(start_date, "%d.%m.%Y")))
)

plot_summary_dataset_yt

htmlwidgets::saveWidget(plot_summary_dataset_yt, file = paste0(directory, "/plot_summary_dataset_yt.html"))

```

Twitter {data-navmenu="Trends Over Time"}
=====================================

Column {.tabset}
-----------------------------------------------------------------------

### **TWEETS AND RETWEETS**

```{r}
plot_over_time_tw_tweets_and_retweets <- ggplotly(
  time_dataset_tw %>%
    mutate(
      week = as.Date(cut(as.Date(date), breaks = "week", start.on.monday = TRUE)) + 4
    ) %>%
    group_by(entity_name, week) %>%
    summarise(end_of_week_posts = max(cumulative_posts_and_retweets)) %>%
    ungroup() %>%
    ggplot(aes(x = week, y = end_of_week_posts, color = entity_name)) +
    geom_line() +
    geom_point(size = 0.8) +
    geom_vline(aes(xintercept = as.numeric(election_date)), color = "#db1d0b") +
    geom_text(aes(x = election_date, y = 0.2, label = "elections"), color = "#03457f", size = 4) +
    theme_minimal() +
    scale_y_continuous(
      breaks = seq(0, 30000, 1000),
      labels = seq(0, 30000, 1000)
    ) +
    scale_x_date(date_breaks = "1 months", date_labels = "%d.%m.%y") +
    coord_cartesian(xlim = c(start_date, end_date), expand = TRUE) +
    theme(legend.title = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1)) +
    xlab(element_blank()) +
    ylab("Total Tweets and Retweets") +
  	labs(color = "User") +
    ggtitle(paste("Combined Tweets and Retweets (based on Twitter API) since", format(start_date, "%d.%m.%Y")))
)

plot_over_time_tw_tweets_and_retweets

htmlwidgets::saveWidget(plot_over_time_tw_tweets_and_retweets, file = paste0(directory, "/plot_over_time_tw_tweets_and_retweets.html"))

```

### **TWEETS**

```{r}
plot_over_time_tw_tweets <- ggplotly(
  time_dataset_tw %>%
    mutate(
      week = as.Date(cut(as.Date(date), breaks = "week", start.on.monday = TRUE)) + 4
    ) %>%
    group_by(entity_name, week) %>%
    summarise(end_of_week_posts = max(cumulative_posts)) %>%
    ungroup() %>%
    ggplot(aes(x = week, y = end_of_week_posts, color = entity_name)) +
    geom_line() +
    geom_point(size = 0.8) +
    geom_vline(aes(xintercept = as.numeric(election_date)), color = "#db1d0b") +
    geom_text(aes(x = election_date, y = 0.2, label = "elections"), color = "#03457f", size = 4) +
    theme_minimal() +
    scale_y_continuous(
      breaks = seq(0, 30000, 1000),
      labels = seq(0, 30000, 1000)
    ) +
    scale_x_date(date_breaks = "1 months", date_labels = "%d.%m.%y") +
    coord_cartesian(xlim = c(start_date, end_date), expand = TRUE) +
    theme(legend.title = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1)) +
  	labs(color = "User") +
    xlab(element_blank()) +
    ylab("Total Tweets (original posts, replies and quotes)") +
    ggtitle(paste("Tweets over time (based on Twitter API) since", format(start_date, "%d.%m.%Y")))
)

plot_over_time_tw_tweets

htmlwidgets::saveWidget(plot_over_time_tw_tweets, file = paste0(directory, "/plot_over_time_tw_tweets.html"))

```

### **RETWEETS**

```{r}
plot_over_time_tw_retweets <- ggplotly(
  time_dataset_tw %>%
    mutate(
      week = as.Date(cut(as.Date(date), breaks = "week", start.on.monday = TRUE)) + 4
    ) %>%
    group_by(entity_name, week) %>%
    summarise(end_of_week_posts = max(cumulative_retweets)) %>%
    ungroup() %>%
    ggplot(aes(x = week, y = end_of_week_posts, color = entity_name)) +
    geom_line() +
    geom_point(size = 0.8) +
    geom_vline(aes(xintercept = as.numeric(election_date)), color = "#db1d0b") +
    geom_text(aes(x = election_date, y = 0.2, label = "elections"), color = "#03457f", size = 4) +
    theme_minimal() +
    scale_y_continuous(
      breaks = seq(0, 30000, 1000),
      labels = seq(0, 30000, 1000)
    ) +
    scale_x_date(date_breaks = "1 months", date_labels = "%d.%m.%y") +
    coord_cartesian(xlim = c(start_date, end_date), expand = TRUE) +
    theme(legend.title = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1)) +
    xlab(element_blank()) +
    ylab("Total Retweets (excluding original posts, replies and quotes)") +
  	labs(color = "User") +
    ggtitle(paste("Total Retweets only (based on Twitter API) since", format(start_date, "%d.%m.%Y")))
)

plot_over_time_tw_retweets

htmlwidgets::saveWidget(plot_over_time_tw_retweets, file = paste0(directory, "/plot_over_time_tw_retweets.html"))

```

### **INTERACTIONS**

```{r}
plot_over_time_tw_interactions <- ggplotly(
  time_dataset_tw %>%
    mutate(
      week = as.Date(cut(as.Date(date), breaks = "week", start.on.monday = TRUE)) + 4
    ) %>%
    group_by(entity_name, week) %>%
    summarise(end_of_week_interactions_thousands = max(cumulative_interactions_thousands)) %>%
    ungroup() %>%
    ggplot(aes(x = week, y = end_of_week_interactions_thousands, color = entity_name)) +
    geom_line() +
    geom_point(size = 0.8) +
    geom_vline(aes(xintercept = as.numeric(election_date)), color = "#db1d0b") +
    geom_text(aes(x = election_date, y = 0.2, label = "elections"), color = "#03457f", size = 4) +
    theme_minimal() +
    scale_y_continuous(
      breaks = seq(0, 10000, 250),
      labels = seq(0, 10000, 250)
    ) +
    scale_x_date(date_breaks = "1 months", date_labels = "%d.%m.%y") +
    coord_cartesian(xlim = c(start_date, end_date), expand = TRUE) +
    theme(legend.title = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1)) +
    xlab(element_blank()) +
    ylab("Total Interactions (retweet/comment/quote, in thousands)") +
    labs(color = "User") +
    ggtitle(paste("Total Interactions over time (thousands, based on Twitter API) since", format(start_date, "%d.%m.%Y")))
)

plot_over_time_tw_interactions

htmlwidgets::saveWidget(plot_over_time_tw_interactions, file = paste0(directory, "/plot_over_time_tw_interactions.html"))

```

Facebook {data-navmenu="Trends Over Time"}
=====================================

Column {.tabset}
-----------------------------------------------------------------------

### **FACEBOOK POSTS**

```{r}
plot_over_time_fb <- ggplotly(
  time_dataset_fb %>%
    mutate(
      week = as.Date(cut(as.Date(date), breaks = "week", start.on.monday = TRUE)) + 4
    ) %>%
    group_by(entity_name, week) %>%
    summarise(end_of_week_posts = max(cumulative_posts)) %>%
    ungroup() %>%
    ggplot(aes(x = week, y = end_of_week_posts, color = entity_name)) +
    geom_line() +
    geom_point(size = 0.8) +
    geom_vline(aes(xintercept = as.numeric(election_date)), color = "#db1d0b") +
    geom_text(aes(x = election_date, y = 0.2, label = "elections"), color = "#03457f", size = 4) +
    theme_minimal() +
    scale_y_continuous(
      breaks = seq(0, 10000, 250),
      labels = seq(0, 10000, 250)
    ) +
    scale_x_date(date_breaks = "1 months", date_labels = "%d.%m.%y") +
    coord_cartesian(xlim = c(start_date, end_date), expand = TRUE) +
    theme(legend.title = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1)) +
    xlab(element_blank()) +
    ylab("Total FB Posts") +
  	labs(color = "User") +
    ggtitle(paste("Total FB Posts (based on Hlidac Statu database) since", format(start_date, "%d.%m.%Y")))
)

plot_over_time_fb

htmlwidgets::saveWidget(plot_over_time_fb, file = paste0(directory, "/plot_over_time_fb.html"))

```

<!-- ### **TOTAL SPONSORED FACEBOOK POSTS ACROSS TIME** -->

<!-- ```{r} -->
<!-- plot_over_time_fb_sponsored <- ggplotly( -->
<!--   time_dataset_fb %>% -->
<!--     mutate( -->
<!--       week = as.Date(cut(as.Date(date), breaks = "week", start.on.monday = TRUE)) + 4 -->
<!--     ) %>% -->
<!--     group_by(entity_name, week) %>% -->
<!--     summarise(end_of_week_sponsored_posts = max(cumulative_sponsored_posts)) %>% -->
<!--     ungroup() %>% -->
<!--     ggplot(aes(x = week, y = end_of_week_sponsored_posts, color = entity_name)) + -->
<!--     geom_line() + -->
<!--     geom_point(size = 0.8) + -->
<!--     geom_vline(aes(xintercept = as.numeric(election_date)), color = "#db1d0b") + -->
<!--     geom_text(aes(x = election_date, y = 0.2, label = "elections"), color = "#03457f", size = 4) + -->
<!--     theme_minimal() + -->
<!--     scale_y_continuous( -->
<!--       breaks = seq(0, 10000, 250), -->
<!--       labels = seq(0, 10000, 250) -->
<!--     ) + -->
<!--     scale_x_date(date_breaks = "1 months", date_labels = "%d.%m.%y") + -->
<!--     coord_cartesian(xlim = c(start_date, end_date), expand = TRUE) + -->
<!--     theme(legend.title = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1)) + -->
<!--     xlab(element_blank()) + -->
<!--     ylab("Total Sponsored Posts") + -->
<!--   	labs(color = "User") + -->
<!--     ggtitle(paste("Sponsored posts of FB accounts in Hlidac Statu dataset since", format(start_date, "%d.%m.%Y"))) -->
<!-- ) -->

<!-- plot_over_time_fb_sponsored -->

<!-- htmlwidgets::saveWidget(plot_over_time_fb_sponsored, file = paste0(directory, "/plot_over_time_fb_sponsored.html")) -->

<!-- ``` -->

YouTube {data-navmenu="Trends Over Time"}
=====================================

Column {.tabset} 
-----------------------------------------------------------------------

### **YOUTUBE VIDEOS**

```{r}
plot_over_time_yt <- ggplotly(
  time_dataset_yt %>%
    mutate(
      week = as.Date(cut(as.Date(date), breaks = "week", start.on.monday = TRUE)) + 4
    ) %>%
    group_by(entity_name, week) %>%
    summarise(end_of_week_posts = max(cumulative_posts)) %>%
    ungroup() %>%
    ggplot(aes(x = week, y = end_of_week_posts, color = entity_name)) +
    geom_line() +
    geom_point(size = 0.8) +
    geom_vline(aes(xintercept = as.numeric(election_date)), color = "#db1d0b") +
    geom_text(aes(x = election_date, y = 0.2, label = "elections"), color = "#03457f", size = 4) +
    theme_minimal() +
    scale_y_continuous(
      breaks = seq(0, 10000, 50),
      labels = seq(0, 10000, 50)
    ) +
    scale_x_date(date_breaks = "1 months", date_labels = "%d.%m.%y") +
    coord_cartesian(xlim = c(start_date, end_date), expand = TRUE) +
    theme(legend.title = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1)) +
    xlab(element_blank()) +
    ylab("Total Videos") +
  	labs(color = "User") +
    ggtitle(paste("YouTube Videos (based on Hlidac Statu database) since", format(start_date, "%d.%m.%Y")))
)

plot_over_time_yt

htmlwidgets::saveWidget(plot_over_time_yt, file = paste0(directory, "/plot_over_time_yt.html"))

```

```{r cleanup, include=FALSE}
# Because the saveWidget function does not correctly delete the dependency files
# which are used to create individual self-sustaining widgets, we have to delete
# them using R functions. All non-html files in output folder are deleted.

unlink(
  grep(
  x = 
    list.files(
    path = directory,
    recursive = TRUE,
    full.names = TRUE,
  ),
  pattern = "(.html)$",
  invert = TRUE,
  value = TRUE
))

```


