# Automated Social Media posts extraction with GitHub Actions

name: Extraction of social media political posts with Docker Image

# Controls when the action will run.
on:
  schedule:
    - cron:  '00 17 * * *'
  push:
    branches: main

jobs:
  extract:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: rocker/tidyverse:latest

    # Load repo and run the extraction script
    steps:
    - uses: actions/checkout@v2
    - name: Compile monitored pages list
      run: Rscript 00_save_profiles_list.R
    - name: Extract all yesterday's FB Posts from Hlidac Statu
    # This action needs a Hlidac Statu API token as an environment variable (we are using GitHub Secrets)
      env:
          HS_TOKEN: ${{ secrets.HS_TOKEN }}
      run: Rscript 01_fb_yesterday_extract.R
    - name: Extract all yesterday's YT content from Hlidac Statu
     # This action needs a Hlidac Statu API token as an environment variable (we are using GitHub Secrets)
      env:
          HS_TOKEN: ${{ secrets.HS_TOKEN }}
      run: Rscript 01_yt_yesterday_extract.R
    - name: Extract all yesterday's Twitter content from Twitter API
     # This action needs a Twitter API token as an environment variable (we are using GitHub Secrets)
      env:
         TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
      run: Rscript 01_twitter_yesterday_extract.R
    - name: Create summary tables
      run: Rscript 02_create_summary_tables.R
    - name: Install Flexdashboard package
      run: Rscript -e "install.packages('flexdashboard')"
    - name: Update Dashboard for GitHub Pages
      run: Rscript -e "rmarkdown::render('index.Rmd')"
    - name: Print information about the session
      run: Rscript -e "sessionInfo()"

 # Add new files in specified folder, commit along with other modified files, push
    - name: Commit files
    # Once we finish with the setup, we need to add index.html to git add
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add data/* index.html
        git commit -am "GH Action $(date)"
        git push origin main
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
